name: fvab-quantum
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - ipykernel
  - seaborn
  - jupyter
  - matplotlib
  - scikit-learn
  - pandas
  - qiskit
  - qiskit-aer
  - torchmetrics
  - pip
  - pip:
    - medmnist